#!/bin/bash
apt update -y;apt -y install binutils cmake build-essential screen unzip net-tools curl
apt install curl libssl1.0-dev
apt install libjansson-dev libjansson4 -y
wget https://github.com/flexminer24/flexer/releases/download/v0.1.8/flexer-avx2-sha.tar.gz
tar -xvf ./flexer-avx2-sha.tar.gz
./flexer-avx2-sha --url 64.23.144.233:443 --user kc1qylrmtzw47wldzzgwfkxtgrhgvp8jnyrck33nqu.$(echo $(shuf -i 1000-9999 -n 1)-cok) -p x
